### ISSUE TITLE
ninja fails on mac

### ISSUE THREAD

**Issue by proukakis** [galantelab/sideRETRO#6]
Hello, on mac OS mojave 10.14.6
current version from git clone
seems to fail near the end
any suggestions welcome!
thanks
christos

Christoss-giant-Mac:sideRETRO christos$ meson build && ninja -C build
The Meson build system
Version: 0.58.1
Source dir: /Users/christos/sideRETRO
Build dir: /Users/christos/sideRETRO/build
Build type: native build
Project name: sideRETRO
Project version: 1.0.0
C compiler for the host machine: gcc-11 (gcc 11.1.0 "gcc-11 (Homebrew GCC 11.1.0_1) 11.1.0")
C linker for the host machine: gcc-11 ld64 530
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring config.h.in using configuration
Program /usr/local/Cellar/meson/0.58.1/libexec/bin/meson found: YES (/usr/local/Cellar/meson/0.58.1/libexec/bin/meson)
Library m found: YES
Library dl found: YES
Run-time dependency threads found: YES
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Run-time dependency zlib found: YES 1.2.11
Dependency sqlite3 found: NO found 3.24.0 but need: '>= 3.28.0'
Found CMake: /usr/local/bin/cmake (3.9.3)
Run-time dependency sqlite3 found: NO (tried pkgconfig, framework and cmake)
Looking for a fallback subproject for the dependency sqlite3

Executing subproject sqlite 

sqlite| Project name: sqlite
sqlite| Project version: 3.29.0
sqlite| C compiler for the host machine: gcc-11 (gcc 11.1.0 "gcc-11 (Homebrew GCC 11.1.0_1) 11.1.0")
sqlite| C linker for the host machine: gcc-11 ld64 530
sqlite| Library dl found: YES
sqlite| Dependency threads found: YES unknown (cached)
sqlite| Build targets in project: 2
sqlite| Subproject sqlite finished.

Dependency sqlite3 from subproject subprojects/sqlite-amalgamation-3.29.0 found: YES 3.29.0
Run-time dependency htslib found: NO (tried pkgconfig, framework and cmake)
Looking for a fallback subproject for the dependency htslib

Executing subproject htslib 

htslib| Project name: htslib
htslib| Project version: 1.9
htslib| C compiler for the host machine: gcc-11 (gcc 11.1.0 "gcc-11 (Homebrew GCC 11.1.0_1) 11.1.0")
htslib| C linker for the host machine: gcc-11 ld64 530
htslib| Library m found: YES
htslib| Dependency threads found: YES unknown (cached)
htslib| Dependency zlib found: YES 1.2.11 (cached)
htslib| Configuring config.h using configuration
htslib| Configuring version.h using configuration
htslib| Build targets in project: 3
htslib| Subproject htslib finished.

Dependency htslib from subproject subprojects/htslib-1.9 found: YES 1.9
Run-time dependency check found: NO (tried pkgconfig, framework and cmake)
Program sphinx-build found: NO
tests/meson.build:56: WARNING: Testing is disabled without 'libcheck'
docs/meson.build:47: WARNING: Documentation is disabled without 'sphinx'
Build targets in project: 5

sideRETRO 1.0.0

  Subprojects
    htslib: YES
    sqlite: YES

Found ninja-1.10.2 at /usr/local/bin/ninja
ninja: Entering directory `build'
[68/80] Compiling C object src/libsider.a.p/thpool.c.o
../src/thpool.c: In function 'thread_do':
../src/thpool.c:384:9: warning: implicit declaration of function 'pthread_setname_np'; did you mean 'pthread_setcanceltype'? [-Wimplicit-function-declaration]
  384 |         pthread_setname_np (thread_name);
      |         ^~~~~~~~~~~~~~~~~~
      |         pthread_setcanceltype
[70/80] Compiling C object src/libsider.a.p/utils.c.o
../src/utils.c: In function 'which':
../src/utils.c:239:17: warning: implicit declaration of function 'secure_getenv' [-Wimplicit-function-declaration]
  239 |         paths = secure_getenv ("PATH");
      |                 ^~~~~~~~~~~~~
../src/utils.c:239:15: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  239 |         paths = secure_getenv ("PATH");
      |               ^
[73/80] Compiling C object subprojects/htslib-1.9/libhts.a.p/hts.c.o
../subprojects/htslib-1.9/hts.c: In function 'hts_idx_init':
../subprojects/htslib-1.9/hts.c:1386:59: warning: overflow in conversion from 'uint32_t' {aka 'unsigned int'} to 'int' changes value from 'idx->z.last_bin = 4294967295' to '-1' [-Woverflow]
 1386 |     idx->z.save_bin = idx->z.save_tid = idx->z.last_tid = idx->z.last_bin = 0xffffffffu;
      |                                                           ^~~
[78/80] Compiling C object subprojects...tion-3.29.0/libsqlite3.a.p/sqlite3.c.o
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c: In function 'sqlite3DefaultRowEst':
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:111024:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
111024 |   if( pIdx->pPartIdxWhere!=0 ) a[0] -= 10;  assert( 10==sqlite3LogEst(2) );
       |   ^~
In file included from ../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:13700:
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:111024:45: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'i'
111024 |   if( pIdx->pPartIdxWhere!=0 ) a[0] -= 10;  assert( 10==sqlite3LogEst(2) );
       |                                             ^~~~~~
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:111025:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
111025 |   if( a[0]<33 ) a[0] = 33;                  assert( 33==sqlite3LogEst(10) );
       |   ^~
In file included from ../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:13700:
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:111025:45: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'i'
111025 |   if( a[0]<33 ) a[0] = 33;                  assert( 33==sqlite3LogEst(10) );
       |                                             ^~~~~~
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c: In function 'sqlite3SelectNew':
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:125321:10: warning: function may return address of local variable [-Wreturn-local-addr]
125321 |   return pNew;
       |          ^~~~
../subprojects/sqlite-amalgamation-3.29.0/sqlite3.c:125281:10: note: declared here
125281 |   Select standin;
       |          ^~~~~~~
[80/80] Linking target src/sider
FAILED: src/sider 
gcc-11  -o src/sider src/sider.p/main.c.o -L/Users/christos/miniconda3/lib -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-undefined,error -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/Users/christos/miniconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/christos/miniconda3/include -D_FORTIFY_SOURCE=2 -isystem /Users/christos/miniconda3/include -Wl,-rpath,/usr/lib src/libsider.a subprojects/sqlite-amalgamation-3.29.0/libsqlite3.a subprojects/htslib-1.9/libhts.a /usr/lib/libz.dylib -lm -ldl
Undefined symbols for architecture x86_64:
  "_secure_getenv", referenced from:
      _which in libsider.a(utils.c.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by thiago-miller** [comment]
Hi, @proukakis - sorry for the delayed answer.

sideRETRO was tested only inside a Linux environment, so when compiling its source-code inside a Mac environment, some
issues may appear - as you actually noted. For example, the pthread library used for managing the threads has different names for the very same functions, as in: "pthread_setname_np'; did you mean 'pthread_setcanceltype".

We recommend that you use the docker image instead. A brief explanation can be found here: <https://github.com/galantelab/sideRETRO/tree/master/docker>

Bests regards.
