### ISSUE TITLE
Recommended maximum number of samples

### ISSUE THREAD

**Issue by thomasfaraut** [galantelab/sideRETRO#8]
Dear authors,

First thank you for this nice and very nicely documented tool.

I would like to use sideretro on a large set of samples (several hundred samples).
Running the complete sideretro practical workflow on 15 samples was successful resulting in a valid vcf file.

Running sideretro process-sample on 30 samples was successfull but merged-call failed.
I stopped the program after several days: no output generated after several days.
The last ouput to the log file was
cluster.c:672: Clustering abnormal alignments

What would be the recommended workflow.
   Follow your "Practical Workflow" on batches (of 15 samples) and use adhoc script to merge the vcf files (taking advantage of the parental gene information) ?

Thank you in advance for your help,
Thomas

**Comment by thiago-miller** [comment]
Dear, @thomasfaraut, since we already talked about it via email, I will close this topic. Any further questions, I am at your disposal. Best regards!
